Add instance Ord TypeRep missing from base-4.3
haskell-compat/base-orphans pull request #55
Opened 2020-12-08 22:26 UTC by Bodigrim

2020-12-09 12:22 UTC, RyanGlScott requested changes
Good catch!

2020-12-09 12:22 UTC, RyanGlScott commented on src/Data/Orphans.hs
> +    compare (tyConString (typeRepTyCon x)) (tyConString (typeRepTyCon x)) `mappend`
If I understand correctly, this works by first comparing the `TyCon` field followed by the `[TypeRep]` field? If so, it would be worth factoring out the `TyCon` comparison into its own `Ord` instance. (I see that the `Ord TyCon` instance was also introduced in `base-4.4.0.0`, so we could backport that to `base-4.3` in `base-orphans` as well.)

2020-12-09 12:22 UTC, RyanGlScott commented on src/Data/Orphans.hs
> +#if !(MIN_VERSION_base(4,4,0))
A minor thing: can you include this code within the existing `#if !(MIN_VERSION_base(4,4,0))` block [here](https://github.com/haskell-compat/base-orphans/blob/0e0bb7c7a3379c566f2858a74900977a2fe93c6d/src/Data/Orphans.hs#L101-L133)? `Data.Orphans` is a pretty tangled mess of CPP, so minimizing the number of different CPP directives that this module uses goes a long way in helping me navigate the code. Thanks.

2020-12-09 23:36 UTC, RyanGlScott approved these changes

2020-12-09 23:37 UTC, merged

2020-12-09 23:38 UTC, RyanGlScott commented
Thanks!

Let me know if you need this to be released to Hackage soon. If not, I'll wait until I next get around to making Hackage uploads (perhaps when it is closer to the final release of GHC 9.0.1).

2020-12-09 23:58 UTC, Bodigrim commented
I'd appreciate a release soon, if it is not too much trouble. I need this piece to run `tasty` on GHC 7.0.

2020-12-10 00:05 UTC, RyanGlScott commented
I've uploaded [`base-orphans-0.8.4`](http://hackage.haskell.org/package/base-orphans-0.8.4) to Hackage with these changes.

2020-12-10 01:00 UTC, Bodigrim commented
Perfect, thanks!